### ISSUE TITLE
Move CLI to its own package

### ISSUE THREAD

**Issue by passy** [passy/android-lint-summary#18]
I want to be able to test the parser and as far as I know I can't import anything in the tests that's in another `Main`.

**Comment by sindresorhus** [comment]
:+1: Regardless of the limitation, splitting the CLI and API into separate packages makes a lot of sense. I've started doing this with lots of my [packages](https://github.com/sindresorhus/pageres-cli). The end result is more focused readme, tests, and issue tracker.

**Comment by passy** [comment]
Heh, I actually meant its own package-internal module. For a single-purpose thing like this it doesn't make too much sense to even expose the underlying parsing infrastructure. But I definitely want to have the actual meat of this testable. :)

**Comment by sindresorhus** [comment]
It's very common to expose the API. ESLint, JSHint, JSCS, etc, does it. But I guess yours is kinda different as it's not a complete linting tool, but rather a meaty reporter.

**Comment by passy** [comment]
Yup, makes total sense to separate the linter. That's pretty much what I'm leveraging here. If there was no intermediate format, I couldn't do this here.
