### ISSUE TITLE
Java 8 Lambda grammar support

### ISSUE THREAD

**Issue by Piasy** [passy/android-lint-summary#23]
My code use lambda expression(with retrolambda library), and when I run `./gradlew lint`, exception was thrown:  
`java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression`

**Comment by passy** [comment]
@Piasy This is a pretty printer for the output the linter provides not the linter itself.

**Comment by regisd** [comment]
See https://code.google.com/p/android/issues/detail?id=224626
