### ISSUE TITLE
lintSummary task failed at gradle 2.6

### ISSUE THREAD

**Issue by Piasy** [passy/android-lint-summary#24]
When I run the lintSummary task from the project root at gradle 2.6, the following error was thrown:  

``` java
Caused by: java.io.IOException: Cannot run program "android-lint-summary" (in directory 
"/Users/piasy/src/AndroidTDDBootStrap/common-android"): error=2, No such file or directory
at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
```

But when I downgrade the gradle to 2.5, it works fine, seems to be the location aware issue. And below is a gradle log:

``` groovy
20:41:17.857 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result 
Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.
LocationAwareException: Execution failed for task ':common-
android:lintSummary'.] from daemon DaemonInfo{pid=33690, address=[56598fa3-f95c-418c-abfe-cb037a847fef 
port:49779, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, 
context=DefaultDaemonContext[uid=231d849b-123a-4919-a8dc-39a6ebbac6a6,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home,
daemonRegistryDir=/Users/piasy/.gradle/daemon,pid=33690,idleTimeout=10800000,daemonOpts=-
XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-
Duser.country=CN,-Duser.language=zh,-Duser.variant]}.
```

**Comment by passy** [comment]
@Piasy That's the integration with gradle, not the program here. It appears to not be on your path. If that changes through the gradle update, consider using a full path instead.

**Comment by Piasy** [comment]
I'm using the example lint-summary.gradle script, so it's the problem of this gradle file?

**Comment by passy** [comment]
Ah, I see. It's actually in a different repo.

Reading through the [ExecSpec](https://docs.gradle.org/current/javadoc/org/gradle/process/ExecSpec.html#commandLine%28java.lang.Iterable%29) docs I can't find anything related to the `PATH` used, but I thought it would just inherit the parent's environment.

How do you run gradle?

**Comment by Piasy** [comment]
I just cd in the project root, and run `./gradlew :common-android:lintSummary`, where common-android is an Android library module.

**Comment by passy** [comment]
Interesting. And running `android-lint-summary` in the same terminal works?

**Comment by Piasy** [comment]
I tried running `android-lint-summary` directly in the same terminal, it works well, `echo $?` prints 0. So I think it may be the problem of the lint-summary.gradle script.

**Comment by passy** [comment]
Thanks for the report. I was able to reproduce it even though I still don't have any idea of what has changed in gradle to break it. Explicitly requiring bash to look up the path fixes it, though. Here's the diff:
https://github.com/passy/Android-LintSummarySample/commit/d7403205fc423d5c42c5ded97756b6c5aca074e5

**Comment by Piasy** [comment]
Thanks!
